"""Tenant store for awesome-python-auth multi-tenant support.

Provides:
- :class:`Tenant` — the Pydantic model for a tenant record.
- :class:`TenantStore` — abstract interface that multi-tenant applications implement.
- :class:`InMemoryTenantStore` — simple in-memory implementation for testing.

Usage::

    from awesome_python_auth import Tenant, TenantStore, InMemoryTenantStore

    store = InMemoryTenantStore()
    tenant = await store.create_tenant({"name": "Acme Corp", "slug": "acme"})
    await store.associate_user_with_tenant("user-123", tenant.id)
    tenants = await store.get_tenants_for_user("user-123")
"""

from __future__ import annotations

import uuid
from abc import ABC, abstractmethod
from typing import Any

from pydantic import BaseModel, Field


class Tenant(BaseModel):
    """A tenant (organisation/workspace) record."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str
    slug: str | None = None
    logo_url: str | None = None
    metadata: dict[str, Any] | None = None
    is_active: bool = True

    def to_api_dict(self) -> dict[str, Any]:
        """Serialise to the camelCase JSON shape used by the admin API."""
        data: dict[str, Any] = {
            "id": self.id,
            "name": self.name,
            "isActive": self.is_active,
        }
        if self.slug is not None:
            data["slug"] = self.slug
        if self.logo_url is not None:
            data["logoUrl"] = self.logo_url
        if self.metadata is not None:
            data["metadata"] = self.metadata
        return data


class TenantStore(ABC):
    """Abstract store for multi-tenant applications.

    Implement this interface and pass an instance to
    :class:`~awesome_python_auth.config.AuthConfig` as ``tenant_store``.
    """

    # ------------------------------------------------------------------
    # Tenant CRUD
    # ------------------------------------------------------------------

    @abstractmethod
    async def create_tenant(self, data: dict[str, Any]) -> Tenant:
        """Create a new tenant.  The ``id`` is generated by the implementation."""

    @abstractmethod
    async def get_tenant_by_id(self, tenant_id: str) -> Tenant | None:
        """Fetch a tenant by its unique identifier; returns ``None`` when not found."""

    @abstractmethod
    async def get_all_tenants(self) -> list[Tenant]:
        """Return all tenants."""

    @abstractmethod
    async def update_tenant(self, tenant_id: str, data: dict[str, Any]) -> Tenant | None:
        """Partially update a tenant's fields; returns the updated tenant or ``None``."""

    @abstractmethod
    async def delete_tenant(self, tenant_id: str) -> None:
        """Permanently delete a tenant and all its user associations."""

    # ------------------------------------------------------------------
    # User ↔ Tenant membership
    # ------------------------------------------------------------------

    @abstractmethod
    async def associate_user_with_tenant(self, user_id: str, tenant_id: str) -> None:
        """Add *user_id* as a member of *tenant_id*.  Idempotent."""

    @abstractmethod
    async def disassociate_user_from_tenant(self, user_id: str, tenant_id: str) -> None:
        """Remove *user_id* from *tenant_id*.  No-op when the association does not exist."""

    @abstractmethod
    async def get_tenants_for_user(self, user_id: str) -> list[Tenant]:
        """Return all tenants the given user belongs to."""

    @abstractmethod
    async def get_users_for_tenant(self, tenant_id: str) -> list[str]:
        """Return the IDs of all users that belong to the given tenant."""


class InMemoryTenantStore(TenantStore):
    """Simple in-memory tenant store — suitable for testing and examples."""

    def __init__(self) -> None:
        self._tenants: dict[str, Tenant] = {}
        # tenant_id -> set[user_id]
        self._memberships: dict[str, set[str]] = {}

    async def create_tenant(self, data: dict[str, Any]) -> Tenant:
        tenant = Tenant(**data)
        self._tenants[tenant.id] = tenant
        self._memberships.setdefault(tenant.id, set())
        return tenant

    async def get_tenant_by_id(self, tenant_id: str) -> Tenant | None:
        return self._tenants.get(tenant_id)

    async def get_all_tenants(self) -> list[Tenant]:
        return list(self._tenants.values())

    async def update_tenant(self, tenant_id: str, data: dict[str, Any]) -> Tenant | None:
        existing = self._tenants.get(tenant_id)
        if existing is None:
            return None
        updated = existing.model_copy(update=data)
        self._tenants[tenant_id] = updated
        return updated

    async def delete_tenant(self, tenant_id: str) -> None:
        self._tenants.pop(tenant_id, None)
        self._memberships.pop(tenant_id, None)

    async def associate_user_with_tenant(self, user_id: str, tenant_id: str) -> None:
        self._memberships.setdefault(tenant_id, set()).add(user_id)

    async def disassociate_user_from_tenant(self, user_id: str, tenant_id: str) -> None:
        if tenant_id in self._memberships:
            self._memberships[tenant_id].discard(user_id)

    async def get_tenants_for_user(self, user_id: str) -> list[Tenant]:
        result: list[Tenant] = []
        for tenant_id, members in self._memberships.items():
            if user_id in members:
                t = self._tenants.get(tenant_id)
                if t:
                    result.append(t)
        return result

    async def get_users_for_tenant(self, tenant_id: str) -> list[str]:
        return sorted(self._memberships.get(tenant_id, set()))
